version: '3'
services:
        web:
                image: crunch_v1 
                build: .
                ports:
                        - "8016:8080" 
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped