version: '3'
services:
        web:
                image: codecrunch_port_v1
                build: .
                ports:
                        - "4269:8086"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
