version: '3'
services:
        web:
                image: codecrunch_port_v1
                build: .
                ports:
                        - "4269:8086"
                volumes:
                #Local:
                        # - ./volumes:/volumes
                        # - ./instance:/instance
                # AWS:
                        - /home/ubuntu/Code-Crunch/Code-Crunch-Backend/volumes:/volumes
                        - /home/ubuntu/Code-Crunch/Code-Crunch-Backend/instance:/instance
                restart: unless-stopped
